---
title: "Running a retrospective analysis on a FIMS model"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Running a retrospective analysis on a FIMS model}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

```

```{r setup}
library(FIMSdiags)
library(FIMS)
#devtools::load_all()
clear()
```


## Set up FIMS model  
Following the minimal demo vignette, we will set up a FIMS model and run it.  

```{r run_fims_model}
# Load sample data
data("data1")
# Prepare data for FIMS model
data_4_model <- FIMSFrame(data1)

# Create parameters
parameters <- data_4_model |>
  create_default_configurations() |>
  create_default_parameters(data = data_4_model)

# Run the  model with optimization
base_model <- parameters |>
  initialize_fims(data = data_4_model) |>
  fit_fims(optimize = TRUE)

# Clear memory post-run
clear()
```

```{r, retro}
retro_fit <- run_fims_retrospective(years_to_remove = 0:2, 
              data_4_model, parameters, 
              n_cores = 3)

# plot the SSB time series from each model
# NOTE: this doesn't work because we don't have a year value.
#       there's a time column but it's empty
library(ggplot2)
retro_fit[["estimates"]] |>
dplyr::filter(label == "spawning_biomass") |> 
dplyr::select(label, year_i, estimated, retro_year) |>
dplyr::group_by(label, retro_year) |>
dplyr::filter(dplyr::row_number() <= dplyr::n() - retro_year) |>
dplyr::ungroup() |> 
ggplot(aes(x = year_i, y = estimated, group = as.factor(retro_year))) +
geom_line(aes(color = as.factor(retro_year)), linewidth = 1.2) +
stockplotr::theme_noaa(discrete = T)


# get SSB time series from each model
# proof that values are different among models
# retro_fit[["estimates"]] |>
#     dplyr::filter(label == "spawning_biomass") |>
#     dplyr::select(label, year_i, estimated, retro_year) |>
#     tidyr::pivot_wider(names_from = retro_year, values_from = estimated) |>
#     tail()
# SSBtable
#   label            year_i   `0`   `1`   `2`
#   <chr>             <int> <dbl> <dbl> <dbl>
# 1 spawning_biomass     26 2001. 1960. 2213.
# 2 spawning_biomass     27 1939. 1889. 2201.
# 3 spawning_biomass     28 1914. 1854. 2232.
# 4 spawning_biomass     29 1798. 1725. 2153.
# 5 spawning_biomass     30 1901. 1815. 2623.
# 6 spawning_biomass     31 1803. 2315. 3115.

```