# Instructions ----
#' This file follows the format generated by FIMS:::use_testthat_template().
#' Necessary tests include input and output (IO) correctness [IO
#' correctness], edge-case handling [Edge handling], and built-in errors and
#' warnings [Error handling]. See `?FIMS:::use_testthat_template` for more
#' information. Every test should have a @description tag, which can span
#' multiple lines, that will be used in the bookdown report of the results from
#' {testthat}.

# fims_likelihood ----
## Setup ----
# Load or prepare any necessary data for testing
# clear memory
clear()
## Testing how to remove one year of data and run multiple FIMS models
# Load sample data
data("data1")
# Prepare data for FIMS model
data_4_model <- FIMSFrame(data1)
# Create parameters
parameters <- data_4_model |>
  create_default_configurations() |>
  create_default_parameters(data = data_4_model)

# Run the  model with optimization
base_model <- parameters |>
  initialize_fims(data = data_4_model) |>
  fit_fims(optimize = TRUE)


## IO correctness ----
# test values that are returned
# test objects that are returned
test_that("fims_likelihood() works with correct inputs", {
  #' @description Test that fims_likelihood(x) returns y.
  
  like_fit <- run_fims_likelihood(
    model = base_model,
    parameters = parameters,
    data = data1,
    n_cores = 1,
    min = -1,
    max = 1,
    length = 3
  )
  expect_equal(
    object = names(like_fit),
    expected = c("vec", "estimates")
  )

  #' @description Test that fims_likelihood(x) returns y.
  expect_equal(
    object = length(like_fit[["vec"]]),
    expected = 3
  )

### add total likelihood across all groups (TODO: turned off for now while we sort out new group column)
  total <- like_fit$estimates |>
    dplyr::filter(!is.na(lpdf)) |>
    dplyr::group_by(value_log_rzero) |>
    dplyr::distinct(lpdf) |>
    dplyr::summarise(total_like = sum(lpdf)) |> # negative to make negative log likelihood
    dplyr::mutate(label = "Total") |>
    dplyr::select(value_log_rzero, label, total_like)

  #' @description Test that fims_likelihood(x) returns y.
  expect_equal(
    object = total$total_like[1]
    expected = -3231.052
  )

})

## Edge handling ----
# Please remove/comment out the test template below if no edge cases are being tested.
# test_that("fims_likelihood() returns correct outputs for edge cases", {
#   #' @description Test that fims_likelihood(x) returns an error.
#   expect_error(
#     object = fims_likelihood(x)
#   )
# })

## Error handling ----
# Please remove/comment out the test template below if there are no built-in errors/warnings.
# test_that("fims_likelihood() returns correct error messages", {
#   #' @description Test that fims_likelihood(x) returns expected error.
#   expect_error(
#     object = fims_likelihood(x),
#     regexp = "Insert text here that should be in the error message."
#   )
# })
