# Instructions ----
#' This file follows the format generated by FIMS:::use_testthat_template().
#' Necessary tests include input and output (IO) correctness [IO
#' correctness], edge-case handling [Edge handling], and built-in errors and
#' warnings [Error handling]. See `?FIMS:::use_testthat_template` for more
#' information. Every test should have a @description tag, which can span
#' multiple lines, that will be used in the bookdown report of the results from
#' {testthat}.

# fims_retrospective ----
## Setup ----
# Load or prepare any necessary data for testing
# clear memory
clear()
## Testing how to remove one year of data and run multiple FIMS models
# Load sample data
data("data1")
# Prepare data for FIMS model
data_4_model <- FIMSFrame(data1)
# Create parameters
parameters <- data_4_model |>
  create_default_configurations() |>
  create_default_parameters(data = data_4_model)

## IO correctness ----
test_that("fims_retrospective() works with correct inputs", {
  #' @description Test that fims_retrospective(x) returns y.
  
  retro_fit <- run_fims_retrospective(
    years_to_remove = 0:2, 
    data = data1, 
    parameters = parameters, 
    n_cores = 1
    )

  expect_equal(
    object = names(retro_fit),
    expected = c("years_to_remove", "estimates")
  )

  #' @description Test that fims_retrospective(x) returns y.
  expect_equal(
    object = length(retro_fit[["vec"]]),
    expected = 3
  )

retro_ssb <- retro_fit[["estimates"]] |>
    dplyr::filter(label == "spawning_biomass") |>
    dplyr::select(label, year_i, estimated, retro_year) |>
    tidyr::pivot_wider(names_from = retro_year, values_from = estimated) |>
    dplyr::filter(year_i == 31) |>
    dplyr::select(-c(1,2)) |>
    as.numeric()

  #' @description Test that fims_retrospective(x) returns y.
  expect_equal(
    object = retro_ssb,
    expected = c(1803.273, 2315.029, 3115.032),
    tolerance = .1
  )

})

## Error handling ----
# Please remove/comment out the test template below if there are no built-in errors/warnings.
test_that("fims_retrospective() returns correct error messages", {
  #' @description Test that fims_retrospective(x) returns expected error.
  expect_error(
    object = fims_retrospective(x),
    regexp = "Insert text here that should be in the error message."
  )
})
